name: Build and Publish Electron App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run make

      - name: Publish Releases
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
