name: Build and Publish Electron App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for macOS
        run: npm run make -- -m

      - name: Build Electron App for Windows
        run: npm run make -- -w

      - name: Build Electron App for Linux
        run: npm run make -- -l

      - name: Publish Releases
        run: npx electron-forge publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
