name: Build and Publish Electron App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Electron-builder compiler action
        uses: x6pnda/action-electron-compiler@v1.0.1
    
